source "http://rubygems.org"
source "http://gemcutter.org"
gem "i18n"
gem "yajl-ruby"
gem "sinatra"
gem "rack"
gem "thin"
gem "haml"
gem "sass"
gem "rack-cache"  
gem "geokit", :git => "git@github.com:evenwestvang/geokit-gem.git"
gem "mongoid", "2.0.0.rc.7"
gem "bson_ext"
gem "memcache-client"
gem "nokogiri"
gem "amatch"